export { default as ConicalGradient } from "./ConicalGradient";
export { default as Carousel } from "./Carousel";
export { default as Text } from "./Text";
export { default as Divider } from "./Divider";
export { default as Card } from "./Card";
export { default as SkillsCard } from "../screens/Resume/components/SkillsCard";
export { default as SoftSkillsCard } from "../screens/Resume/components/SoftSkillsCard";
export { default as ExperienceCard } from "../screens/Resume/components/ExperienceCard";
export { PortalProvider, Portal, PortalContext } from "./Portal";
export { default as Certification } from "../screens/Resume/components/Certification";
export { default as Achievement } from "../screens/Resume/components/Achievement";
export { default as BottomMenuGate } from "./BottomMenu";
// export { default as Certification } from './Certification';
// export { default as Achievement } from './Achievement';
export { default as View } from "./View";
